# Generated by Django 5.2 on 2025-04-27 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('satwa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memberi',
            fields=[
                ('id_hewan', models.OneToOneField(db_column='id_hewan', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='satwa.hewan')),
                ('jadwal', models.DateTimeField()),
            ],
            options={
                'db_table': 'memberi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jadwal', models.DateTimeField()),
                ('jenis', models.CharField(max_length=50)),
                ('jumlah', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pakan',
                'managed': False,
            },
        ),
    ]
