# Generated by Django 5.2 on 2025-04-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayingWithNeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'playing_with_neon',
                'managed': False,
            },
        ),
    ]
