# Generated by Django 5.2 on 2025-04-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopsi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pembayaran', models.CharField(max_length=10)),
                ('tgl_mulai_adopsi', models.DateField()),
                ('tgl_berhenti_adopsi', models.DateField()),
                ('kontribusi_finansial', models.IntegerField()),
            ],
            options={
                'db_table': 'adopsi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id_adopter', models.UUIDField(primary_key=True, serialize=False)),
                ('total_kontribusi', models.IntegerField()),
            ],
            options={
                'db_table': 'adopter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hewan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'HEWAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('nik', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'individu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organisasi',
            fields=[
                ('npp', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nama_organisasi', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'organisasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'PENGUNJUNG',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PlayingWithNeon',
        ),
    ]
