# Generated by Django 5.2 on 2025-04-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopsi', '0002_adopsi_adopter_hewan_individu_organisasi_pengunjung_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hewan',
        ),
        migrations.DeleteModel(
            name='Pengunjung',
        ),
    ]
