# Generated by Django 5.2 on 2025-04-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopsi', '0003_delete_hewan_delete_pengunjung'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adopsi',
            options={'default_related_name': '+', 'managed': False},
        ),
    ]
