# Generated by Django 5.2 on 2025-04-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopsi', '0004_alter_adopsi_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adopsi',
            options={'managed': False},
        ),
    ]
