# Generated by Django 5.2 on 2025-04-27 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('nama_depan', models.CharField(max_length=50)),
                ('nama_tengah', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_belakang', models.CharField(max_length=50)),
                ('no_telepon', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'pengguna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DokterHewan',
            fields=[
                ('username_dh', models.OneToOneField(db_column='username_dh', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.pengguna')),
                ('no_str', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dokter_hewan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PelatihHewan',
            fields=[
                ('username_lh', models.OneToOneField(db_column='username_lh', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.pengguna')),
                ('id_staf', models.UUIDField()),
            ],
            options={
                'db_table': 'pelatih_hewan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('username_p', models.OneToOneField(db_column='username_p', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.pengguna')),
                ('alamat', models.CharField(max_length=200)),
                ('tgl_lahir', models.DateField()),
            ],
            options={
                'db_table': 'pengunjung',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PenjagaHewan',
            fields=[
                ('username_jh', models.OneToOneField(db_column='username_jh', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.pengguna')),
                ('id_staf', models.UUIDField()),
            ],
            options={
                'db_table': 'penjaga_hewan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StafAdmin',
            fields=[
                ('username_sa', models.OneToOneField(db_column='username_sa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.pengguna')),
                ('id_staf', models.UUIDField()),
            ],
            options={
                'db_table': 'staf_admin',
                'managed': False,
            },
        ),
    ]
