# Generated by Django 5.2 on 2025-04-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spesialisasi',
            fields=[
                ('pk', models.CompositePrimaryKey('username_sh', 'nama_spesialisasi', blank=True, editable=False, primary_key=True, serialize=False)),
                ('nama_spesialisasi', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'spesialisasi',
                'managed': False,
            },
        ),
    ]
