# Generated by Django 5.2 on 2025-04-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatatanMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pemeriksaan', models.DateField()),
                ('diagnosis', models.CharField(blank=True, max_length=100, null=True)),
                ('pengobatan', models.CharField(blank=True, max_length=100, null=True)),
                ('status_kesehatan', models.CharField(max_length=50)),
                ('catatan_tindak_lanjut', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'catatan_medis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JadwalPemeriksaanKesehatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_pemeriksaan_selanjutnya', models.DateField()),
                ('freq_pemeriksaan_rutin', models.IntegerField()),
            ],
            options={
                'db_table': 'jadwal_pemeriksaan_kesehatan',
                'managed': False,
            },
        ),
    ]
